//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string ReferenceNo { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Email { get; set; }
        public string CellNo { get; set; }
        public string Agent { get; set; }
        public string Address { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
