//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTransaction
    {
        public int CustomerTransID { get; set; }
        public Nullable<System.DateTime> TrasnactionDate { get; set; }
        public string ReferenceNo { get; set; }
        public string CustomerName { get; set; }
        public string TransactionDescription { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string CreatedBy { get; set; }
    }
}
